### ISSUE TITLE
Can I render a flight analysis video?

### ISSUE THREAD

**Issue by oaishi** [Hugoch/flights-analysis#1]
Hello, thank you so much for your tutorial. Is it possible to render a video instead of an image? Something similar to this: [https://youtu.be/TIZHn3ECHpM](https://youtu.be/TIZHn3ECHpM)

**Comment by Hugoch** [comment]
Hello @oaishi, yes that would be possible by generating an image per video frame, then assembling that using FFMPEG or equivalent.
I would however advise to use more dedicated tools like Kepler.gl . I did a demonstration of that for work https://youtu.be/YiadlF5jw24?t=2261 . First part I process history static data and animate with time, second part, I stream real-time captured data from planes flying above Paris. Sorry video is French only :(

**Comment by oaishi** [comment]
Thank you so much for your detailed answer. And the demonstration was brilliant!
